### PR TITLE
add winter is cold

### PR DESCRIPTION
**Pull request by haneenaatheeq**

### CODE REVIEW

**Comment by haxzie** [comment]
Hey @haneenaatheeq  The file should be a Markdown file. ie. the extension **.md**, currently the file has the extension .txt  which won't be able to parse the contents in frontmatter.

**Comment by haxzie** [comment]
Discard the previous comment, You already have a merged PR and your profile is up on the website.

**Comment by haxzie** [comment]
You already have a merged PR for your profile. You can close this.

**Comment by haneenaatheeq** [comment]
Can't I change d extension to md in dis itself or shud I start from scratch?

**Comment by haxzie** [comment]
No need actually. You have already submitted a PR before. And your profile is live @ gitme.js.org

**Pull request closed without merging**
